### ISSUE TITLE
TypeError: decode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by frdmn** [side2k/email2pb#1]
I'm using postfix 2.11.0 on Ubuntu 14.04

Here's the `mail.log`:

``` shell
Jun  8 13:50:25 chewbacca postfix/pickup[30280]: 5A8582540B68: uid=0 from=<root@chewbacca.company.com>
Jun  8 13:50:25 chewbacca postfix/cleanup[32233]: 5A8582540B68: message-id=<20150608115025.5A8582540B68@chewbacca.company.com>
Jun  8 13:50:25 chewbacca postfix/qmgr[5290]: 5A8582540B68: from=<root@chewbacca.company.com>, size=361, nrcpt=1 (queue active)
Jun  8 13:50:25 chewbacca postfix/local[32234]: 5A8582540B68: to=<push@chewbacca.company.com>, relay=local, delay=0.15, delays=0/0/0/0.15, dsn=5.3.0, status=bounced (Command died with status 1: "/var/spool/postfix/email2pb/email2pb". Command output: Traceback (most recent call last):   File "/var/spool/postfix/email2pb/email2pb.py", line 50, in <module>     body_part = body_part.decode(part.get_content_charset()) TypeError: decode() argument 1 must be string, not None )
Jun  8 13:50:25 chewbacca postfix/cleanup[32233]: 7FEEF2540B90: message-id=<20150608115025.7FEEF2540B90@chewbacca.company.com>
Jun  8 13:50:25 chewbacca postfix/bounce[32237]: 5A8582540B68: sender non-delivery notification: 7FEEF2540B90
Jun  8 13:50:25 chewbacca postfix/qmgr[5290]: 7FEEF2540B90: from=<>, size=2676, nrcpt=1 (queue active)
Jun  8 13:50:25 chewbacca postfix/qmgr[5290]: 5A8582540B68: removed
Jun  8 13:50:25 chewbacca postfix/cleanup[32233]: 80DF025400F6: message-id=<20150608115025.7FEEF2540B90@chewbacca.company.com>
Jun  8 13:50:25 chewbacca postfix/qmgr[5290]: 80DF025400F6: from=<>, size=2818, nrcpt=1 (queue active)
Jun  8 13:50:25 chewbacca postfix/local[32234]: 7FEEF2540B90: to=<root@chewbacca.company.com>, relay=local, delay=0.01, delays=0/0/0/0, dsn=2.0.0, status=sent (forwarded as 80DF025400F6)
Jun  8 13:50:25 chewbacca postfix/qmgr[5290]: 7FEEF2540B90: removed
Jun  8 13:50:25 chewbacca dovecot: lda(info@company.com): msgid=<20150608115025.7FEEF2540B90@chewbacca.company.com>: saved mail to INBOX
Jun  8 13:50:25 chewbacca postfix/pipe[32238]: 80DF025400F6: to=<info@company.com>, orig_to=<root@chewbacca.company.com>, relay=dovecot, delay=0.03, delays=0/0/0/0.02, dsn=2.0.0, status=sent (delivered via dovecot service)
Jun  8 13:50:25 chewbacca postfix/qmgr[5290]: 80DF025400F6: removed
```

I'm not familiar with Python programming so I don't know about a workaround for this.

Any ideas?

**Comment by side2k** [comment]
@frdmn I've committed a fix for this, but I can't test it myself. Would be grateful if you checked it.

**Comment by frdmn** [comment]
@side2k Impressed about your response time! Wow.

Unfortunately there's a new issue now:

```
Jun  8 14:02:18 chewbacca postfix/local[1348]: D066E2540B68: to=<push@chewbacca.company.com>, relay=local, delay=0.18, delays=0.02/0.01/0/0.16, dsn=5.3.0, status=bounced (Command died with status 1: "/var/spool/postfix/email2pb/email2pb". Command output: Traceback (most recent call last):   File "/var/spool/postfix/email2pb/email2pb.py", line 69, in <module>     cmdline += [item.encode(DEFAULT_ENCODING) for sublist in header_pairs for item in sublist] UnicodeDecodeError: 'ascii' codec can't decode byte 0xb5 in position 5: ordinal not in range(128) )
```

**Comment by side2k** [comment]
@frdmn hmm. Heres another fix.

**Comment by frdmn** [comment]
@side2k Still not :/

```
Jun  8 14:20:24 chewbacca postfix/local[3719]: 3BF6A2540B68: to=<push@chewbacca.yeahwh.at>, relay=local, delay=0.18, delays=0.02/0.01/0/0.15, dsn=5.3.0, status=bounced (Command died with status 1: "/var/spool/postfix/email2pb/email2pb". Command output: Traceback (most recent call last):   File "/var/spool/postfix/email2pb/email2pb.py", line 54, in <module>     body_part = body_part.decode() UnicodeDecodeError: 'ascii' codec can't decode byte 0xb5 in position 0: ordinal not in range(128) )
```

**Comment by frdmn** [comment]
:+1:
